spring.application.name=springboot-data-jpa

#if database exist
#spring.datasource.url=jdbc:mysql://localhost:3306/moviedb
spring.datasource.url=jdbc:mysql://localhost:3306/moviedb?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=1234

#to create a table 

spring.jpa.hibernate.ddl-auto=update
#everyt time drop and create table if we use create command

#to display the sql query in console

spring.jpa.show-sql=true


#To Format Query in SQL

spring.jpa.properties.hibernate.format_sql = true;